CREATE OR REPLACE USER jorge IDENTIFIED BY 'jorge';
GRANT ALL ON *.* TO jorge;

CREATE DATABASE tienda;

USE tienda;

CREATE TABLE productos (id VARCHAR(10) PRIMARY KEY, nombre VARCHAR(30) NULL DEFAULT NULL, descripcion VARCHAR(200) NULL DEFAULT NULL, precio INTEGER(11) NULL DEFAULT NULL);